### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by dbogdanov** [andrepolischuk/keep#10]
I cannot run this application (I am not experienced with Electron). I've followed the steps for building the app. 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle keep@0.0.0~prestart: keep@0.0.0
6 silly lifecycle keep@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle keep@0.0.0~start: keep@0.0.0
8 verbose lifecycle keep@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle keep@0.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/dbogdanov/install/keep/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle keep@0.0.0~start: CWD: /home/dbogdanov/install/keep
11 silly lifecycle keep@0.0.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle keep@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle keep@0.0.0~start: Failed to exec start script
14 verbose stack Error: keep@0.0.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid keep@0.0.0
16 verbose cwd /home/dbogdanov/install/keep
17 error Linux 4.4.0-38-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error keep@0.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the keep@0.0.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the keep package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs keep
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls keep
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by andrepolischuk** [comment]
Try to install latest npm version. What os you use?

**Comment by dbogdanov** [comment]
Ubuntu 16.04

**Comment by andrepolischuk** [comment]
Try to pull latest changes, install deps and run npm start. Or try install the electron globally and run start.

**Comment by dbogdanov** [comment]
Now it works, thank you!
