### ISSUE TITLE
Electron Error

### ISSUE THREAD

**Issue by ShockvaWe** [andrepolischuk/keep#21]
Electron 1.7.6 is installed on my linux mint 18.2 correctly.
But when i type npm install on keep's directory it gives this error.

```
> electron@1.7.6 postinstall /home/mrnoone/Programs/keep/node_modules/electron
> node install.js

/home/mrnoone/Programs/keep/node_modules/electron/install.js:48
  throw err
  ^

Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrnoone/.npm/_logs/2017-09-17T13_55_59_145Z-debug.log
```

**Comment by andrepolischuk** [comment]
@ShockvaWe I found some related info, may be they help you install

* https://github.com/electron/electron/issues/9307
* https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron
